using Aetherphone.Core.Telephony.Contracts;

namespace Aetherphone.Core.Telephony;

// AetherStream's watch-along signalling - rides CallSignalRouter's existing RealtimeConnection
// (same wss /rt socket, same CallControl JSON envelope as call.*) rather than opening a second
// WebSocket per user. Mirrors CallSignalRouter's own OnControl dispatch shape, just filtered to
// the stream.* family. Server-side policy (mutual-contact + block checks, room capacity, auto-leave
// on switching rooms) is enforced entirely server-side - this class only reflects what the server
// already decided, it doesn't re-implement any of that. stream.nearby is the one deliberate
// exception to the contact-gated join path - zone-scoped discovery by design, see RequestNearby.
internal sealed class StreamSignalRouter : IDisposable
{
    private readonly CallSignalRouter calls;

    public StreamSignalRouter(CallSignalRouter calls)
    {
        this.calls = calls;
        calls.Connection.ControlReceived += OnControl;
    }

    public event Action<CallControl>? Joined;
    public event Action<CallControl>? Declined;
    public event Action<CallControl>? RosterReceived;

    // {userId} of whoever just left/was kicked, sent to everyone still in the room alongside a
    // fresh stream.roster. The roster broadcast alone already updates Roster - this event exists
    // so the host can also drop that userId from PendingRequests/PendingQueueSuggestions, which
    // stream.roster says nothing about (see WatchAlongSession.OnLeft).
    public event Action<CallControl>? LeftReceived;
    public event Action<CallControl>? Ended;
    public event Action<CallControl>? StateReceived;
    public event Action<CallControl>? NearbyReceived;

    // Host-approval extension (see SignalType.StreamJoinRequest's doc comment).
    public event Action<CallControl>? JoinRequested;
    public event Action<CallControl>? JoinPending;

    // Shared-queue extension (see SignalType.StreamQueueSuggest's doc comment) - QueueSuggested
    // reaches the host, QueueSuggestionResult reaches the original suggester.
    public event Action<CallControl>? QueueSuggested;
    public event Action<CallControl>? QueueSuggestionResult;

    // Host-kick extension (see SignalType.StreamKick's doc comment) - only ever raised on the
    // client that was actually kicked.
    public event Action<CallControl>? Kicked;

    public bool Connected => calls.Connected;

    // Host only - the server treats a viewer's stream.state as a no-op, and the first one from an
    // actual host creates the room ("go live"); later ones update it. Do not treat yourself as
    // hosting until the echoed stream.state comes back through StateReceived - see spec note on
    // the live-ack. screenPosition/screenYaw/screenScale are omitted (left null) when the host's
    // own screen isn't active - see CallControl's ScreenX/Y/Z/Yaw/Scale doc comment. territoryId
    // lets the server answer stream.nearby queries from other players in the same zone.
    // approvalRequired is the host-approval extension's own field - always sent (not optional) so
    // the server has a current answer for "is this room open or gated" on every publish, not just
    // the first one.
    public void PublishState(string url, double positionSeconds, bool paused, uint territoryId,
        bool approvalRequired, Vector3? screenPosition = null, float? screenYaw = null, float? screenScale = null)
    {
        calls.Send(new CallControl
        {
            Type = SignalType.StreamState, Url = url, PositionSeconds = positionSeconds, Paused = paused,
            TerritoryId = territoryId, ApprovalRequired = approvalRequired,
            ScreenX = screenPosition?.X, ScreenY = screenPosition?.Y, ScreenZ = screenPosition?.Z,
            ScreenYaw = screenYaw, ScreenScale = screenScale,
        });
    }

    // Host only - decide a pending stream.joinRequest (see WatchAlongSession.PendingRequests).
    public void Approve(string userId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamApprove, UserId = userId });
    }

    public void Deny(string userId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamDeny, UserId = userId });
    }

    // Viewer only - suggestionId is generated by the caller (WatchAlongSession.SuggestQueueItem),
    // not the server, since a viewer can have more than one suggestion outstanding. Max 64 chars,
    // 2s cooldown per connection, 32 outstanding per room, enforced server-side.
    public void SuggestQueueItem(string url, string suggestionId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamQueueSuggest, Url = url, SuggestionId = suggestionId });
    }

    // Host only - decide a pending stream.queueSuggestion.
    public void ApproveQueueSuggestion(string suggestionId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamQueueApprove, SuggestionId = suggestionId });
    }

    public void DenyQueueSuggestion(string suggestionId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamQueueDeny, SuggestionId = suggestionId });
    }

    // Host only - force-remove a specific participant.
    public void Kick(string userId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamKick, UserId = userId });
    }

    // 2s per-connection cooldown is enforced server-side - callers must not auto-retry declines in
    // a tight loop.
    public void Join(string hostId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamJoin, HostId = hostId });
    }

    // Zone-scoped discovery - separate from Join's mutual-contact/block-gated path entirely. The
    // server answers with whoever is currently hosting (via PublishState) in this same territory,
    // no contact relationship required. Response arrives through NearbyReceived.
    public void RequestNearby(uint territoryId)
    {
        calls.Send(new CallControl { Type = SignalType.StreamNearby, TerritoryId = territoryId });
    }

    // No hostId needed - the server already knows which room this connection is in. From the host
    // this ends the stream for everyone.
    public void Leave()
    {
        calls.Send(new CallControl { Type = SignalType.StreamLeave });
    }

    private void OnControl(CallControl message)
    {
        switch (message.Type)
        {
            case SignalType.StreamJoined:
                Joined?.Invoke(message);
                return;
            case SignalType.StreamDeclined:
                Declined?.Invoke(message);
                return;
            case SignalType.StreamRoster:
                RosterReceived?.Invoke(message);
                return;
            case SignalType.StreamLeft:
                LeftReceived?.Invoke(message);
                return;
            case SignalType.StreamState:
                StateReceived?.Invoke(message);
                return;
            case SignalType.StreamEnded:
                Ended?.Invoke(message);
                return;
            case SignalType.StreamNearbyRoster:
                NearbyReceived?.Invoke(message);
                return;
            case SignalType.StreamJoinRequest:
                JoinRequested?.Invoke(message);
                return;
            case SignalType.StreamJoinPending:
                JoinPending?.Invoke(message);
                return;
            case SignalType.StreamQueueSuggestion:
                QueueSuggested?.Invoke(message);
                return;
            case SignalType.StreamQueueSuggestionResult:
                QueueSuggestionResult?.Invoke(message);
                return;
            case SignalType.StreamKicked:
                Kicked?.Invoke(message);
                return;
        }
    }

    public void Dispose()
    {
        calls.Connection.ControlReceived -= OnControl;
    }
}
