using System.Text.Json.Serialization;
using Aetherphone.Core.Aethernet.Contracts;

namespace Aetherphone.Core.Aethernet;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(ChallengeRequest))]
[JsonSerializable(typeof(ChallengeResponse))]
[JsonSerializable(typeof(VerifyRequest))]
[JsonSerializable(typeof(AuthResponse))]
[JsonSerializable(typeof(VerifyResponse))]
[JsonSerializable(typeof(XivAuthStartRequest))]
[JsonSerializable(typeof(XivAuthStartResponse))]
[JsonSerializable(typeof(XivAuthPollRequest))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(UpdateProfileRequest))]
[JsonSerializable(typeof(UpdateTimeZoneRequest))]
[JsonSerializable(typeof(CreatePostRequest))]
[JsonSerializable(typeof(ReactRequest))]
[JsonSerializable(typeof(PostDto))]
[JsonSerializable(typeof(FeedPage))]
[JsonSerializable(typeof(UserSearchResult))]
[JsonSerializable(typeof(UploadUrlRequest))]
[JsonSerializable(typeof(UploadUrlResponse))]
[JsonSerializable(typeof(CreateGramRequest))]
[JsonSerializable(typeof(CommentDto))]
[JsonSerializable(typeof(CreateCommentRequest))]
[JsonSerializable(typeof(CommentPage))]
[JsonSerializable(typeof(AnalyticsBatchRequest))]
[JsonSerializable(typeof(AnalyticsEventDto))]
[JsonSerializable(typeof(AnalyticsAckDto))]
[JsonSerializable(typeof(ReportRequest))]
[JsonSerializable(typeof(VelvetProfileDto))]
[JsonSerializable(typeof(UpdateVelvetProfileRequest))]
[JsonSerializable(typeof(GateAcceptRequest))]
[JsonSerializable(typeof(VelvetPostDto))]
[JsonSerializable(typeof(VelvetFeedPage))]
[JsonSerializable(typeof(CreateVelvetPostRequest))]
[JsonSerializable(typeof(VelvetDiscoverPage))]
[JsonSerializable(typeof(VelvetConnectionDto))]
[JsonSerializable(typeof(VelvetConnectionPage))]
[JsonSerializable(typeof(VelvetThreadDto))]
[JsonSerializable(typeof(VelvetThreadPage))]
[JsonSerializable(typeof(VelvetMessageDto))]
[JsonSerializable(typeof(VelvetMessagePage))]
[JsonSerializable(typeof(SendVelvetMessageRequest))]
[JsonSerializable(typeof(VelvetMediaUrlDto))]
[JsonSerializable(typeof(VelvetTypingDto))]
[JsonSerializable(typeof(VelvetCommentDto))]
[JsonSerializable(typeof(VelvetCommentPage))]
[JsonSerializable(typeof(CreateVelvetCommentRequest))]
[JsonSerializable(typeof(CreateFeedbackRequest))]
[JsonSerializable(typeof(FeedbackDto))]
[JsonSerializable(typeof(NotificationDto))]
[JsonSerializable(typeof(NotificationPage))]
[JsonSerializable(typeof(DevBoardCardDto))]
[JsonSerializable(typeof(DevBoardCards))]
[JsonSerializable(typeof(CreateDevCardRequest))]
[JsonSerializable(typeof(UpdateDevCardRequest))]
[JsonSerializable(typeof(MoveDevCardRequest))]
[JsonSerializable(typeof(DevChatMessageDto))]
[JsonSerializable(typeof(DevChatPage))]
[JsonSerializable(typeof(SendDevChatMessageRequest))]
[JsonSerializable(typeof(DevMediaUrlDto))]
[JsonSerializable(typeof(PollDto))]
[JsonSerializable(typeof(PollTranslationDto))]
[JsonSerializable(typeof(PollPage))]
[JsonSerializable(typeof(PollVoteRequest))]
[JsonSerializable(typeof(Dictionary<string, string>))]
internal sealed partial class AethernetJsonContext : JsonSerializerContext
{
}
